# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sala da Ana
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Aqui você vai conhecer um pouco mais sobre mim e sobre
  os meus passos profissionais sendo disseminadora de Qualidade de Software
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.anapaulavale.com.br" # the base hostname & protocol for your site
twitter_username: apvale
github_username:  apvale

# Build settings
markdown: kramdown
